### ISSUE TITLE
It can't work for any new unreal engine developer.

### ISSUE THREAD

**Issue by ivarss** [satisfactorymodding/unreal-linker#3]
Due to changes to the unreal engine org setup at github any new user that signs up to the org gets put in a new mirror org.
Meaning this linker won't recognize the new unreal engine org as viable and allow access to the custom unreal builds.

**Comment by mircearoata** [comment]
This is addressed in https://github.com/satisfactorymodding/unreal-linker/commit/df190ef44d3af772361f92b3b0f64e4dbc4937cf, which should be deployed soon :tm:

**Comment by mircearoata** [comment]
It has now been deployed
